print("Hello 'python!'")
print('Hello "python!"')
print("Hello \npython!")
print("Hello \bpython!")
print("Hello \tpython!")
print("\n\n")
print("Hello 'python!'")
print('Hello "python!"')
print(r"Hello \npython!")
print(R"Hello \bpython!")
print(r"Hello \tpython!")