mystr = "This is python"
print(mystr)           

print(mystr[0])
print(mystr[-3])
print(mystr[0:7])
print(mystr[-3:]) 

print(mystr.strip())
print(mystr.lower())
print(mystr.upper())
print(mystr.replace('i','I'))   
print(mystr.capitalize())
print(mystr.casefold())
print(mystr.count("is"))
print(mystr.startswith("This"))
print(mystr.endswith("."))
print(mystr.index("p"))
print(mystr.isalpha())
print(mystr.isalnum())
print(mystr.isdigit())
print(mystr.islower())
print(mystr.isupper())  
print(mystr.title())